static const char *g_shader_fragment_quad = ""
#if defined(USE_LD)
"quad_430.frag.glsl"
#else
"#version 430\n"
"layout(location=0)uniform vec3[4] o;"
"in vec2 v;"
"out vec4 t;"
"void main()"
"{"
"vec2 i=v;"
"if(o[3].y>1.)"
"{"
"i.x*=o[3].y;"
"}"
"else"
"{"
"i.y/=o[3].y;"
"}"
"vec3 v=normalize(o[1]),a=normalize(cross(v,o[2])),c=normalize(i.x*a+i.y*normalize(cross(a,v))+v);"
"float s=dot(-o[0],c),n=1.+sin(o[3].x/4444.)*.1;"
"vec3 r=s*c+o[0];"
"float l=dot(r,r);"
"if(l<=n)"
"{"
"vec3 v=(s-sqrt(n*n-l*l))*c+o[0];"
"t=vec4(v*dot(v,vec3(1.)),1.);"
"}"
"else"
"{"
"t=vec4(.0,.0,.0,1.);"
"}"
"}"
#endif
"";
