static const char *g_shader_fragment_quad = ""
#if defined(USE_LD)
"quad_430.frag.glsl"
#else
"#version 430\n"
"layout(location=0)uniform vec3[4] o;"
"in vec2 v;"
"out vec4 t;"
"void main()"
"{"
"vec2 i=v;"
"if(o[3].g>1.)"
"{"
"i.r*=o[3].g;"
"}"
"else"
"{"
"i.g/=o[3].g;"
"}"
"vec3 v=normalize(o[1]),l=normalize(cross(v,o[2])),c=normalize(i.r*l+i.g*normalize(cross(l,v))+v);"
"float s=dot(-o[0],c),n=1.+sin(o[3].r/4444.)*.1;"
"vec3 a=s*c+o[0];"
"float r=dot(a,a);"
"if(r<=n)"
"{"
"vec3 v=(s-sqrt(n*n-r*r))*c+o[0];"
"t=vec4(v*dot(v,vec3(1.)),1.);"
"}"
"else"
"{"
"t=vec4(.0,.0,.0,1.);"
"}"
"}"
#endif
"";
