static const char *g_shader_fragment_quad = ""
#if defined(USE_LD)
"quad_430.frag.glsl"
#else
"#version 430\n"
"layout(location=0)uniform vec3 e[4];"
"in vec2 v;"
"out vec4 l;"
"void main()"
"{"
"vec2 o=v;"
"if(e[3].g>1.)o.r*=e[3].g;"
"else o.g/=e[3].g;"
"vec3 v=normalize(e[1]),t=normalize(cross(v,e[2])),i=normalize(o.r*t+o.g*normalize(cross(t,v))+v);"
"float n=dot(-e[0],i),c=1.+sin(e[3].r/4444.)*.1;"
"vec3 a=n*i+e[0];"
"float r=dot(a,a);"
"if(r<=c)"
"{"
"vec3 o=(n-sqrt(c*c-r*r))*i+e[0];"
"l=vec4(o*dot(o,vec3(1)),1.);"
"}"
"else l=vec4(.0,.0,.0,1.);"
"}"
#endif
"";
